kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      name: rest
      nodePort: 31000
    - port: 9300
      targetPort: 9300
      name: inter-node
      nodePort: 31001 
