services:
  api:
    build: 
      context: ./backend
    container_name: api
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:13.16
    
    container_name: db
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql


  web:
    build:
      context: ./frontend
    container_name: web
    ports:
      - "3000:80"
    
    depends_on:
      - api

volumes:
  db_data:

