apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: myapp
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000 
      targetPort: 5000 
  selector:
    app: backend