apiVersion: v1
data:
  init.sql: |-
    CREATE TABLE users (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100)
    );

    INSERT INTO users (name) VALUES ('Bianca'), ('Andrei'), ('Maria');
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: postgres-init
  namespace: myapp