apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
  namespace: myapp
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: db
  clusterIP: None
  selector:
    app: postgres
