apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-standard
  namespace: myapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic