apiVersion: v1
kind: ResourceQuota
metadata:
  name: myapp-quota
  namespace: myapp
spec:
  hard:
    requests.cpu: "2.5"
    requests.memory: "2.5Gi"
    limits.cpu: "5"
    limits.memory: "5Gi"
    pods: "5"
    persistentvolumeclaims: "2"
