apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic
  namespace: myapp
provisioner: kubernetes.io/azure-file
reclaimPolicy: Delete
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
allowVolumeExpansion: true
parameters:
  skuName: Standard_LRS
  secretName: azure-secret
  secretNamespace: myapp